# Generated by Django 6.0.3 on 2026-03-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatsense_app', '0004_seatlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_pin',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='bookingseat',
            unique_together={('booking', 'seat')},
        ),
    ]
