# Generated by Django 6.0.3 on 2026-03-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatsense_app', '0007_feedbackreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditorium',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
