# Generated by Django 6.0.3 on 2026-03-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatsense_app', '0008_remove_auditorium_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='speakers/')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='events', to='seatsense_app.speaker'),
        ),
    ]
