# Generated by Django 6.0.3 on 2026-03-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatsense_app', '0009_speaker_event_speakers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='bio',
        ),
        migrations.AlterField(
            model_name='speaker',
            name='image',
            field=models.ImageField(upload_to='speakers/'),
        ),
    ]
