# Generated by Django 6.0.3 on 2026-03-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatsense_app', '0010_remove_speaker_bio_alter_speaker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g. 2 Hours, 3 Days, Full Day', max_length=50, null=True),
        ),
    ]
