# Generated by Django 6.0.3 on 2026-03-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatsense_app', '0011_event_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(blank=True, choices=[('1', '1 Hour'), ('1.5', '1.5 Hours'), ('2', '2 Hours'), ('2.5', '2.5 Hours'), ('3', '3 Hours'), ('3.5', '3.5 Hours'), ('4', '4 Hours'), ('5', '5 Hours'), ('6', '6 Hours'), ('8', '8 Hours / Full Day'), ('12', '12 Hours / Half Day'), ('24', '1 Day (24 Hours)'), ('48', '2 Days (48 Hours)'), ('72', '3 Days (72 Hours)')], help_text='Select the estimated duration of the event', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='events/'),
        ),
    ]
